spring.application.name=user

spring.datasource.url=jdbc:postgresql://localhost:5432/demousersdb
spring.datasource.username=postgres
spring.datasource.password=${POSTGRESQL_PASSWORD}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

